.TH "Base" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Base \- Classes base das isotermas
.SH SYNOPSIS
.br
.PP
.SS "Módulos"

.in +1c
.ti -1c
.RI "\fB<br>\fP"
.br
.ti -1c
.RI "\fB<br>\fP"
.br
.ti -1c
.RI "\fB<br>\fP"
.br
.ti -1c
.RI "\fBOneParameter\fP"
.br
.ti -1c
.RI "\fBThreeParameters\fP"
.br
.ti -1c
.RI "\fBTwoParameters\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Grupo de Classes de onde sao derivadas as classes com os modelos de isotermas\&. 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
