.TH "Five_Parameters" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Five_Parameters \- Isotermas com cinco parametros
.SH SYNOPSIS
.br
.PP
.SH "Descrição detalhada"
.PP 
Grupo de Isotermas que possuem cinco parametros\&. 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
