.TH "Four_Parameters" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Four_Parameters \- Isotermas com quatro parametros
.SH SYNOPSIS
.br
.PP
.SS "Módulos"

.in +1c
.ti -1c
.RI "\fBBaudu\fP"
.br
.ti -1c
.RI "\fBFritzSchlunderIV\fP"
.br
.ti -1c
.RI "\fBMarczewskiJaroniec\fP"
.br
.ti -1c
.RI "\fBWeberVanVliet\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Grupo de Isotermas que possuem quatro parametros\&. 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
