.TH "FritzSchlunderV" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FritzSchlunderV \- Classe com as equacoes da isoterma de \fBFritz\fP - Schlunder - V\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <FritzSchlunderV\&.h>\fP
.PP
Subclasse de \fBFiveParameters\fP e \fBIsothermTemplate< FritzSchlunderV >\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBDefineIdentity\fP ('Fritz \- Schlunder \- V', ID::FritzSchlunderV)"
.br
.RI "Definicao de \fBID\fP para esta classe para fins de identificacao de erros\&. "
.ti -1c
.RI "\fBFritzSchlunderV\fP ()=default"
.br
.ti -1c
.RI "\fBFritzSchlunderV\fP (const \fBFritzSchlunderV\fP &_fritz_schlunder_v)=default"
.br
.RI "Construtora de cópia\&. "
.ti -1c
.RI "virtual \fB~FritzSchlunderV\fP ()=default"
.br
.RI "Destrutora\&. "
.ti -1c
.RI "\fBFritzSchlunderV\fP (const Real &, const Real &, const Real &, const Real &, const Real &)"
.br
.RI "Construtora com os parametros que definem a isoterma de \fBFritzSchlunderV\fP\&. "
.ti -1c
.RI "\fBFritzSchlunderV\fP & \fBoperator=\fP (const \fBFritzSchlunderV\fP &)=default"
.br
.RI "Sobrecarga do operador =\&. "
.ti -1c
.RI "Real \fBQmax\fP () const"
.br
.RI "Funcao que informa o valor da capacidade maxima de adsorcao\&. "
.ti -1c
.RI "Real \fBK1\fP () const"
.br
.RI "Funcao que retorna o coeficiente associado a constante de \fBFritz\fP - Schlunder - V\&. "
.ti -1c
.RI "Real \fBK2\fP () const"
.br
.RI "Funcao que retorna o parametro da equacao de \fBFritz\fP - Schlunder - V\&. "
.ti -1c
.RI "Real \fBK3\fP () const"
.br
.RI "Funcao que retorna o parametro da equacao de \fBFritz\fP - Schlunder - V\&. "
.ti -1c
.RI "Real \fBK4\fP () const"
.br
.RI "Funcao que retorna o parametro da equacao de \fBFritz\fP - Schlunder - V\&. "
.ti -1c
.RI "void \fBQmax\fP (const Real &_qmax)"
.br
.RI "Funcao para alterar a capacidade maxima de adsorcao\&. "
.ti -1c
.RI "void \fBK1\fP (const Real &_k1)"
.br
.RI "Funcao que altera o coeficiente associado a constante da isoterma de \fBFritz\fP – Schlunder - V\&. "
.ti -1c
.RI "void \fBK2\fP (const Real &_k2)"
.br
.RI "Funcao para alterar o valor associado a constante da isoterma de \fBFritz\fP – Schlunder - V\&. "
.ti -1c
.RI "void \fBK3\fP (const Real &_k3)"
.br
.RI "Funcao para alterar o valor associado ao expoente da isoterma de \fBFritz\fP – Schlunder - V\&. "
.ti -1c
.RI "void \fBK4\fP (const Real &_k4)"
.br
.RI "Funcao para alterar o valor associado ao expoente da isoterma de \fBFritz\fP – Schlunder - V\&. "
.ti -1c
.RI "Real \fBQe\fP (const Real &, const Real &) const"
.br
.RI "Funcao que calcula a quantidade de sorcao no equilibrio\&. "
.ti -1c
.RI "Real \fBQe\fP (const Real &_c) const override"
.br
.ti -1c
.RI "virtual std::unique_ptr< \fBIsotherm\fP > \fBCloneImplementation\fP () const override"
.br
.in -1c
.SS "Outros membros herdados"
.SH "Descrição detalhada"
.PP 
Classe com as equacoes da isoterma de \fBFritz\fP - Schlunder - V\&. 

Isoterma com tres parametros, $ q_{max} $, $ K_1 $, $ K_2 $, $ K_3 $ e $ K_4 $, cujas formulas sao as seguintes: \\begin{align} [Q_e(C_e, T) = \\frac{q_{max}C_e^{K_3}}{K_1+K_2C_e^{K_4}}] \\end{align} Um artigo de referencia pode ser encontrado \fCaqui\fP\&. 
.PP
\fBAutores\fP
.RS 4
Joao Flavio Vieira de Vasconcellos 
.RE
.PP
\fBVersão\fP
.RS 4
1\&.0 
.RE
.PP
\fBData\fP
.RS 4
2022 
.RE
.PP
\fBBug\fP
.RS 4
Nao ha bugs conhecidos\&.
.RE
.PP
.PP
\fBCopyright\fP
.RS 4
GNU Public License\&. 
.RE
.PP

.SH "Construtores e Destrutores"
.PP 
.SS "FritzSchlunderV::FritzSchlunderV ()\fC [default]\fP"

.PP
Construtora default\&. 
.PP
Uso: 
.PP
.nf
FritzSchlunderV  var;

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros para esta funcao 
.RE
.PP

.SS "FritzSchlunderV::FritzSchlunderV (const \fBFritzSchlunderV\fP & _fritz_schlunder_v)\fC [default]\fP"

.PP
Construtora de cópia\&. Uso: 
.PP
.nf
FritzSchlunderV  var;
FritzSchlunderV  var1(var);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_orig\fP Variavel do tipo \fBFritz\fP - Schlunder - V original\&. 
.RE
.PP

.SS "FritzSchlunderV::FritzSchlunderV (const Real & _qmax, const Real & _k1, const Real & _k2, const Real & _k3, const Real & _k4)"

.PP
Construtora com os parametros que definem a isoterma de \fBFritzSchlunderV\fP\&. Uso: 
.PP
.nf
double QMAX(1\&.0);
double K1(1\&.0);
double K2(1\&.0);
Sips  var1(Q1, K1, K2);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_qmax\fP Capacidade maxima de adsorcao\&. 
.br
\fI_k1\fP Coeficiente da isortema de \fBFritz\fP - Schlunder - V\&. 
.br
\fI_k2\fP Coeficiente da isoterma de \fBFritz\fP - Schlunder - V\&. 
.br
\fI_k3\fP Expoente da isoterma de \fBFritz\fP - Schlunder - V\&. 
.br
\fI_k4\fP Expoente da isoterma de \fBFritz\fP - Schlunder - V\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_qmax\fP < 0\&. 
.br
\fI_k1\fP <= 0\&. 
.br
\fI_k2\fP <= 0\&. 
.br
\fI0\fP < _k3 < 1 \&. 
.br
\fI0\fP < _k4 < 1 \&. 
.RE
.PP

.SH "Funções membros"
.PP 
.SS "virtual std::unique_ptr< \fBIsotherm\fP > FritzSchlunderV::CloneImplementation () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implementa \fBIsotherm\fP\&.
.SS "FritzSchlunderV::DefineIdentity ('Fritz \- Schlunder \- V', ID::FritzSchlunderV)"

.PP
Definicao de \fBID\fP para esta classe para fins de identificacao de erros\&. 
.SS "Real FritzSchlunderV::K1 () const\fC [inline]\fP"

.PP
Funcao que retorna o coeficiente associado a constante de \fBFritz\fP - Schlunder - V\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double k1 = var1\&.K1();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor do coeficiente associado a constante de \fBFritz\fP - Schlunder - V\&. 
.RE
.PP

.SS "void FritzSchlunderV::K1 (const Real & _k1)\fC [inline]\fP"

.PP
Funcao que altera o coeficiente associado a constante da isoterma de \fBFritz\fP – Schlunder - V\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double k1(2\&.0);
var1\&.K1(k1);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k1\fP Novo valor do coeficiente associado a constante da isoterma de \fBFritz\fP – Schlunder - V\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_k1\fP <= 0\&. 
.RE
.PP

.SS "Real FritzSchlunderV::K2 () const\fC [inline]\fP"

.PP
Funcao que retorna o parametro da equacao de \fBFritz\fP - Schlunder - V\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double k2 = var1\&.K2();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor do parametro da equacao de \fBFritz\fP - Schlunder - V\&. 
.RE
.PP

.SS "void FritzSchlunderV::K2 (const Real & _k2)\fC [inline]\fP"

.PP
Funcao para alterar o valor associado a constante da isoterma de \fBFritz\fP – Schlunder - V\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double k2(3\&.0);
var1\&.K2(k2);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k2\fP Novo valor associado a constante da isoterma de \fBFritz\fP – Schlunder - V\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_k2\fP <= 0\&. 
.RE
.PP

.SS "Real FritzSchlunderV::K3 () const\fC [inline]\fP"

.PP
Funcao que retorna o parametro da equacao de \fBFritz\fP - Schlunder - V\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double k3 = var1\&.K3();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor do parametro da equacao de \fBFritz\fP - Schlunder - V\&. 
.RE
.PP

.SS "void FritzSchlunderV::K3 (const Real & _k3)\fC [inline]\fP"

.PP
Funcao para alterar o valor associado ao expoente da isoterma de \fBFritz\fP – Schlunder - V\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double k3(3\&.0);
var1\&.K3(k3);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k3\fP Novo valor associado ao expoente da isoterma de \fBFritz\fP – Schlunder - V\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI0\fP < _k3 < 1\&. 
.RE
.PP

.SS "Real FritzSchlunderV::K4 () const\fC [inline]\fP"

.PP
Funcao que retorna o parametro da equacao de \fBFritz\fP - Schlunder - V\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double k4 = var1\&.K4();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor do parametro da equacao de \fBFritz\fP - Schlunder - V\&. 
.RE
.PP

.SS "void FritzSchlunderV::K4 (const Real & _k4)\fC [inline]\fP"

.PP
Funcao para alterar o valor associado ao expoente da isoterma de \fBFritz\fP – Schlunder - V\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double k4(3\&.0);
var1\&.K4(k4);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k4\fP Novo valor associado ao expoente da isoterma de \fBFritz\fP – Schlunder - V\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI0\fP < _k4 < 1\&. 
.RE
.PP

.SS "\fBFritzSchlunderV\fP & FritzSchlunderV::operator= (const \fBFritzSchlunderV\fP &)\fC [default]\fP"

.PP
Sobrecarga do operador =\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2);
FritzSchlunderV  var2 = var1;

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_orig\fP Variavel do tipo \fBFritzSchlunderV\fP original\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Cópia de _orig\&. 
.RE
.PP

.SS "Real FritzSchlunderV::Qe (const Real & _ce, const Real &) const\fC [virtual]\fP"

.PP
Funcao que calcula a quantidade de sorcao no equilibrio\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2);
double ce(1\&.0);
double qe = var1\&.Qe(ce);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_c\fP Concentracao do soluto\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor da quantidade de sorcao no equilibrio\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_c\fP < 0\&. 
.RE
.PP

.PP
Implementa \fBIsotherm\fP\&.
.SS "Real FritzSchlunderV::Qe (const Real & _c) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Reimplementa \fBIsotherm\fP\&.
.SS "Real FritzSchlunderV::Qmax () const\fC [inline]\fP"

.PP
Funcao que informa o valor da capacidade maxima de adsorcao\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double q1 = var1\&.Qmax();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor da capacidade maxima de adsorcao\&. 
.RE
.PP

.SS "void FritzSchlunderV::Qmax (const Real & _qmax)\fC [inline]\fP"

.PP
Funcao para alterar a capacidade maxima de adsorcao\&. Uso: 
.PP
.nf
FritzSchlunderV  var1(QMAX, K1, K2, K3, K4);
double q1(3\&.0);
var1\&.Qmax(q1);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_qmax\fP Novo valor da capacidade maxima de adsorcao\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_qmax\fP < 0\&. 
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
