.TH "HarkinJura" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HarkinJura \- Classe com as equacoes da isoterma de \fBHarkinJura\fP  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <HarkinJura\&.h>\fP
.PP
Subclasse de \fBTwoParameters\fP e \fBIsothermTemplate< HarkinJura >\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBDefineIdentity\fP ('HarkinJura', ID::HarkinJura)"
.br
.RI "Definicao de \fBID\fP para esta classe para fins de identificacao de erros\&. "
.ti -1c
.RI "\fBHarkinJura\fP ()=default"
.br
.RI "Construtora default\&. "
.ti -1c
.RI "\fBHarkinJura\fP (const \fBHarkinJura\fP &_orig)=default"
.br
.RI "Construtora de copia\&. "
.ti -1c
.RI "virtual \fB~HarkinJura\fP ()=default"
.br
.RI "Destrutora\&. "
.ti -1c
.RI "\fBHarkinJura\fP (const Real &_k1, const Real &_k2)"
.br
.RI "Construtora com os parametros que definem a isoterma de \fBHarkinJura\fP\&. "
.ti -1c
.RI "\fBHarkinJura\fP & \fBoperator=\fP (const \fBHarkinJura\fP &_orig)=default"
.br
.RI "Sobrecarga do operador =\&. "
.ti -1c
.RI "Real \fBK1\fP () const"
.br
.RI "Funcao que informa o valor da constante da isoterma de Harkin-Jura\&. "
.ti -1c
.RI "Real \fBK2\fP () const"
.br
.RI "Funcao que informa o valor da constante da isoterma de Harkin-Jura\&. "
.ti -1c
.RI "void \fBK1\fP (const Real &_k1)"
.br
.RI "Funcao para alterar o valor da constante da isoterma de Harkin-Jura\&. "
.ti -1c
.RI "void \fBK2\fP (const Real &_k2)"
.br
.RI "Funcao para alterar o valor da constante da isoterma de Harkin-Jura\&. "
.ti -1c
.RI "Real \fBQe\fP (const Real &_c, const Real &_temp=0) const override"
.br
.RI "Funcao que calcula a quantidade de sorcao no equilibrio\&. "
.ti -1c
.RI "virtual std::unique_ptr< \fBIsotherm\fP > \fBCloneImplementation\fP () const override"
.br
.in -1c
.SS "Outros membros herdados"
.SH "Descrição detalhada"
.PP 
Classe com as equacoes da isoterma de \fBHarkinJura\fP 

Isoterma com dois parametros, $ K_1 $ e $ K_2 $, cujas formulas sao as seguintes: \\begin{align} [\\frac{1}{Q_e(C_e, T)^{2}} = \\frac{K_2 - 1}{K_1}log(C_e)] \\end{align} Um artigo de referencia pode ser encontrado \fCaqui\fP\&. 
.PP
\fBAutores\fP
.RS 4
Iasmim Barboza Storck 
.PP
Lara Botelho Brum 
.PP
Luan Rodrigues Soares de Souza 
.PP
Joao Flavio Vieira de Vasconcellos 
.RE
.PP
\fBVersão\fP
.RS 4
1\&.0 
.RE
.PP
\fBData\fP
.RS 4
2022 
.RE
.PP
\fBBug\fP
.RS 4
Nao ha bugs conhecidos\&.
.RE
.PP
.PP
\fBCopyright\fP
.RS 4
GNU Public License\&. 
.RE
.PP

.SH "Construtores e Destrutores"
.PP 
.SS "HarkinJura::HarkinJura ()\fC [default]\fP"

.PP
Construtora default\&. Uso: 
.PP
.nf
HarkinJura  var;

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros para esta funcao 
.RE
.PP

.SS "HarkinJura::HarkinJura (const \fBHarkinJura\fP & _orig)\fC [default]\fP"

.PP
Construtora de copia\&. Uso: 
.PP
.nf
HarkinJura  var;
HarkinJura  var1(var);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_orig\fP Variavel do tipo \fBHarkinJura\fP original\&. 
.RE
.PP

.SS "HarkinJura::HarkinJura (const Real & _k1, const Real & _k2)"

.PP
Construtora com os parametros que definem a isoterma de \fBHarkinJura\fP\&. Uso: 
.PP
.nf
Real k1(1\&.0);
Real k2(1\&.0);            
HarkinJura  var1(k1, k2);              

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k1\fP Constante da isoterma de Harkin-Jura\&. 
.br
 
.br
\fI_k2\fP Constante da isoterma de Harkin-Jura\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_k1\fP <= 0\&. 
.br
\fI_k2\fP <= 0\&. 
.RE
.PP

.SH "Funções membros"
.PP 
.SS "virtual std::unique_ptr< \fBIsotherm\fP > HarkinJura::CloneImplementation () const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Implementa \fBIsotherm\fP\&.
.SS "HarkinJura::DefineIdentity ('HarkinJura', ID::HarkinJura)"

.PP
Definicao de \fBID\fP para esta classe para fins de identificacao de erros\&. 
.SS "Real HarkinJura::K1 () const\fC [inline]\fP"

.PP
Funcao que informa o valor da constante da isoterma de Harkin-Jura\&. Uso: 
.PP
.nf
HarkinJura  var1(k1, k2);              
Real _k1 = var1\&.K1();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor da constante da isoterma de Harkin-Jura\&. 
.RE
.PP

.SS "void HarkinJura::K1 (const Real & _k1)\fC [inline]\fP"

.PP
Funcao para alterar o valor da constante da isoterma de Harkin-Jura\&. Uso: 
.PP
.nf
HarkinJura  var1(k1, k2);              
Real k11(3\&.0);
var1\&.K1(k11);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k1\fP Novo valor da constante da isoterma de Harkin-Jura\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_k1\fP <= 0\&. 
.RE
.PP

.SS "Real HarkinJura::K2 () const\fC [inline]\fP"

.PP
Funcao que informa o valor da constante da isoterma de Harkin-Jura\&. Uso: 
.PP
.nf
HarkinJura  var1(k1, k2);              
Real _k2 = var1\&.K2();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor da constante da isoterma de Harkin-Jura\&. 
.RE
.PP

.SS "void HarkinJura::K2 (const Real & _k2)\fC [inline]\fP"

.PP
Funcao para alterar o valor da constante da isoterma de Harkin-Jura\&. Uso: 
.PP
.nf
HarkinJura  var1(k1, k2);              
Real _k22(2\&.0);
var1\&.K2(_k22);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k2\fP Novo valor da constante da isoterma de Harkin-Jura\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_k2\fP <= 0\&. 
.RE
.PP

.SS "\fBHarkinJura\fP & HarkinJura::operator= (const \fBHarkinJura\fP & _orig)\fC [default]\fP"

.PP
Sobrecarga do operador =\&. Uso: 
.PP
.nf
HarkinJura  var1(k1, k2);              
HarkinJura  var2 = var1;

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_orig\fP Variavel do tipo \fBHarkinJura\fP original\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Copia de _orig\&. 
.br
 
.RE
.PP

.SS "Real HarkinJura::Qe (const Real & _c, const Real & _temp = \fC0\fP) const\fC [override]\fP, \fC [virtual]\fP"

.PP
Funcao que calcula a quantidade de sorcao no equilibrio\&. Uso: 
.PP
.nf
HarkinJura  var1(k1, k2);              
Real ce(1\&.0);
Real qe = var1\&.Qe(ce);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_c\fP Concentracao do soluto\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor da quantidade de sorcao no equilibrio\&. 
.br
 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_c\fP < 0\&. 
.RE
.PP

.PP
Implementa \fBIsotherm\fP\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
