.TH "ID" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ID
.SH SYNOPSIS
.br
.PP
.SS "Tipos Públicos"

.in +1c
.ti -1c
.RI "enum { \fBIsotherm\fP = 0, \fBOneParameter\fP, \fBTwoParameters\fP, \fBThreeParameters\fP, \fBFourParameters\fP, \fBFiveParameters\fP, \fBHenry\fP = 100, \fBDubininRadushkevich\fP = 200, \fBElovich\fP, \fBFreundlich\fP, \fBHarkinJura\fP, \fBHalsey\fP, \fBJovanovic\fP, \fBLangmuir\fP, \fBTemkin\fP, \fBHill\fP = 300, \fBHillDeBoer\fP, \fBRedlichPeterson\fP, \fBSips\fP, \fBKiselev\fP, \fBFowlerGuggenheim\fP, \fBHollKrich\fP, \fBJossens\fP, \fBKhan\fP, \fBToth\fP, \fBViethSladek\fP, \fBFritzSchlunder\fP, \fBLangmuirFreundlich\fP, \fBBrouersSotolongo\fP, \fBKobleCorrigan\fP, \fBBrunauerEmmettTeller\fP, \fBRadkePrausnitsI\fP, \fBRadkePrausnitsII\fP, \fBRadkePrausnitsIII\fP, \fBLangmuirJovanovic\fP, \fBMacMillanTeller\fP, \fBUnilan\fP, \fBValenzuelaMyers\fP, \fBBaudu\fP = 400, \fBFritzSchlunderIV\fP, \fBMarczewskiJaroniec\fP, \fBWeberVanVliet\fP, \fBFritzSchlunderV\fP = 500, \fBFrenkelHalseyHill\fP, \fBHenderson\fP }"
.br
.in -1c
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBID\fP (const \fBID\fP &)=default"
.br
.ti -1c
.RI "\fBID\fP & \fBoperator=\fP (const \fBID\fP &)=default"
.br
.ti -1c
.RI "virtual std::string \fBclassName\fP () const"
.br
.ti -1c
.RI "virtual UInt \fBclassID\fP () const"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
