.TH "IsothermLib/include/Error/IsoException.h" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsothermLib/include/Error/IsoException.h
.SH SYNOPSIS
.br
.PP
\fC#include <exception>\fP
.br
\fC#include <string>\fP
.br
\fC#include <Misc/Configure\&.h>\fP
.br
\fC#include <Misc/SourceInfo\&.h>\fP
.br

.SS "Componentes"

.in +1c
.ti -1c
.RI "class \fBIsoException\fP"
.br
.RI "Classe para tratar as exceptions do programa\&. "
.in -1c
.SS "Enumerações"

.in +1c
.ti -1c
.RI "enum \fBIsoExceptionIndex\fP { \fBBadCoefficient\fP = 0, \fBBadCeLEZero\fP, \fBBadCeLTZero\fP, \fBBadCeGEOne\fP, \fBBadCeGEK2\fP, \fBBadK1LEZero\fP, \fBBadK1LTZero\fP, \fBBadK2LEZero\fP, \fBBadK2LTZero\fP, \fBBadK3LEZero\fP, \fBBadK3LTZero\fP, \fBBadK4LEZero\fP, \fBBadK4LTZero\fP, \fBBadK1LTOne\fP, \fBBadK2LEOne\fP, \fBBadK3GTOne\fP, \fBBadK3GEOne\fP, \fBBadQmaxLEZero\fP, \fBBadTempLEZero\fP, \fBBadRGasLEZero\fP, \fBBadResult\fP, \fBBadOverFlow\fP, \fBBadLogCeGTK2\fP, \fBConvergenceProblem\fP, \fBBadThetaGEOne\fP, \fBBadThetaLEZero\fP, \fBBadKCeK1LEOne\fP }"
.br
.in -1c
.SH "Descrição detalhada"
.PP 

.PP
\fBAutor\fP
.RS 4
Joao Flavio Vieira de Vasconcellos 
.RE
.PP
\fBVersão\fP
.RS 4
1\&.0 
.RE
.PP
\fBData\fP
.RS 4
2022 
.RE
.PP
\fBBug\fP
.RS 4
Nao ha bugs conhecidos 
.RE
.PP

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
