.TH "IsoException" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsoException \- Classe para tratar as exceptions do programa\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <IsoException\&.h>\fP
.PP
Subclasse de std::exception\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBIsoException\fP (const \fBSourceInfo\fP &, const std::string &, const IsoExceptionIndex &, const std::string &='', const std::string &='')"
.br
.ti -1c
.RI "\fBIsoException\fP (const std::string &_msg, const std::string &_funct, const std::string &_arquivo, const UInt &_linha)"
.br
.ti -1c
.RI "\fBIsoException\fP (const \fBIsoException\fP &)=default"
.br
.ti -1c
.RI "virtual const char * \fBwhat\fP () const  throw ()"
.br
.in -1c
.SS "Amigas"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &, const \fBIsoException\fP &)"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Classe para tratar as exceptions do programa\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
