.TH "IsothermTemplate< T >" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
IsothermTemplate< T > \- Classe que gerencia o nome e detalhes sobre cada constante dos modelos das isotermas\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Isotherm\&.h>\fP
.PP
Subclasse de \fBIsotherm\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "auto \fBbegin\fP () const"
.br
.ti -1c
.RI "auto \fBend\fP () const"
.br
.ti -1c
.RI "auto \fBbegin\fP ()"
.br
.ti -1c
.RI "auto \fBend\fP ()"
.br
.ti -1c
.RI "auto \fBcbegin\fP () const"
.br
.ti -1c
.RI "auto \fBcend\fP () const"
.br
.ti -1c
.RI "auto \fBrbegin\fP () const"
.br
.ti -1c
.RI "auto \fBrend\fP () const"
.br
.ti -1c
.RI "auto \fBrbegin\fP ()"
.br
.ti -1c
.RI "auto \fBrend\fP ()"
.br
.ti -1c
.RI "auto \fBcrbegin\fP () const"
.br
.ti -1c
.RI "auto \fBcrend\fP () const"
.br
.in -1c
.SS "Membros Protegidos"

.in +1c
.ti -1c
.RI "const VecPairString & \fBInfoIsotherm\fP () const override"
.br
.ti -1c
.RI "\fBIST_NAMESPACE_OPEN\fP VecPairString \fBinfoIsotherm\fP"
.br
.ti -1c
.RI "\fBIST_NAMESPACE_OPEN\fP VecPairString \fBinfoIsotherm\fP"
.br
.ti -1c
.RI "VecPairString \fBinfoIsotherm\fP"
.br
.ti -1c
.RI "\fBIST_NAMESPACE_OPEN\fP VecPairString \fBinfoIsotherm\fP"
.br
.ti -1c
.RI "VecPairString \fBinfoIsotherm\fP"
.br
.in -1c
.SS "Atributos Estáticos Protegidos"

.in +1c
.ti -1c
.RI "static VecPairString \fBinfoIsotherm\fP"
.br
.in -1c
.SS "Outros membros herdados"
.SH "Descrição detalhada"
.PP 

.SS "template<typename T>
.br
class IsothermTemplate< T >"Classe que gerencia o nome e detalhes sobre cada constante dos modelos das isotermas\&. 


.PP
\fBAutores\fP
.RS 4
Lara Botelho Brum 
.PP
Luan Rodrigues Soares de Souza 
.PP
Joao Flavio Vieira de Vasconcellos 
.RE
.PP
\fBVersão\fP
.RS 4
1\&.0 
.RE
.PP
\fBData\fP
.RS 4
2021 
.RE
.PP
\fBBug\fP
.RS 4
Nao ha bugs conhecidos\&.
.RE
.PP
.PP
\fBCopyright\fP
.RS 4
GNU Public License\&. 
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
