.TH "NewtonRaphson" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NewtonRaphson \- Metodo de Newton-Rapshon
.SH SYNOPSIS
.br
.PP
.SS "Definições de Tipos"

.in +1c
.ti -1c
.RI "typedef std::function< Real(Real)> \fBNRFunction\fP"
.br
.in -1c
.SS "Funções"

.in +1c
.ti -1c
.RI "Real \fBNewtonRaphson\fP (NRFunction, const Real &)"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Programacao do metodo Newton-Raphson para o calculo de raizes de funcoes\&. 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
