.TH "OneParameter" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
OneParameter \- Classe base para todas as classes com um unico parametro\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OneParameter\&.h>\fP
.PP
Subclasse de \fBIsotherm\fP\&.
.PP
Superclasse de \fBHenry\fP\fC [virtual]\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBDefineIdentity\fP ('OneParameter', ID::OneParameter)"
.br
.RI "Definicao de \fBID\fP para esta classe para fins de identificacao de erros\&. "
.ti -1c
.RI "\fBOneParameter\fP (const \fBOneParameter\fP &)=default"
.br
.RI "Construtora de copia que sera utilizada nas classes derivadas\&. "
.ti -1c
.RI "virtual \fB~OneParameter\fP ()=default"
.br
.RI "Destrutora\&. "
.ti -1c
.RI "\fBOneParameter\fP (const Real &=0\&.0)"
.br
.RI "Construtora de um parametro utilizada nas classes derivadas\&. "
.in -1c
.SS "Outros membros herdados"
.SH "Descrição detalhada"
.PP 
Classe base para todas as classes com um unico parametro\&. 


.PP
\fBAutores\fP
.RS 4
Lara Botelho Brum 
.PP
Luan Rodrigues Soares de Souza 
.PP
Joao Flavio Vieira de Vasconcellos 
.RE
.PP
\fBVersão\fP
.RS 4
1\&.0 
.RE
.PP
\fBData\fP
.RS 4
2022 
.RE
.PP
\fBBug\fP
.RS 4
Nao ha bugs conhecidos\&.
.RE
.PP
.PP
\fBCopyright\fP
.RS 4
GNU Public License\&. 
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
