.TH "Redlich" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Redlich \- Classe com as equacoes da isoterma de \fBRedlich\fP - Peterson\&.  

.SH SYNOPSIS
.br
.PP
.SH "Descrição detalhada"
.PP 
Classe com as equacoes da isoterma de \fBRedlich\fP - Peterson\&. 

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
