.TH "SourceInfo" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SourceInfo
.SH SYNOPSIS
.br
.PP
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBSourceInfo\fP (const \fBSourceInfo\fP &)=default"
.br
.ti -1c
.RI "\fBSourceInfo\fP (const std::string &, const long &, const std::string &)"
.br
.ti -1c
.RI "std::string \fBFileLocation\fP () const"
.br
.ti -1c
.RI "long \fBLinePosition\fP () const"
.br
.ti -1c
.RI "std::string \fBFunctionName\fP () const"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
