.TH "TestSuit" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TestSuit
.SH SYNOPSIS
.br
.PP
.PP
Subclasse de testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test, testing::Test e testing::Test\&.
.SS "Atributos Públicos"

.in +1c
.ti -1c
.RI "TestIsotherm \fBisotherm_1\fP"
.br
.ti -1c
.RI "TestIsotherm \fBisotherm_2\fP = TestIsotherm(QMAX, K1, K2, K3, K4)"
.br
.ti -1c
.RI "TestIsotherm \fBisotherm_3\fP = TestIsotherm(isotherm_2)"
.br
.in -1c
.SS "Atributos Protegidos"

.in +1c
.ti -1c
.RI "const Real \fBCE\fP = 1\&.32730"
.br
.ti -1c
.RI "const Real \fBQMAX\fP = 6\&.05758"
.br
.ti -1c
.RI "const Real \fBK1\fP = 0\&.217337"
.br
.ti -1c
.RI "const Real \fBK2\fP = 0\&.885359e\-1"
.br
.ti -1c
.RI "const Real \fBK3\fP = 0\&.0169304"
.br
.ti -1c
.RI "const Real \fBK4\fP = 0\&.746286e\-1"
.br
.ti -1c
.RI "const Real \fBQMAXNovo\fP = 34\&.548"
.br
.ti -1c
.RI "const Real \fBK1Novo\fP = 98\&.1e\-03"
.br
.ti -1c
.RI "const Real \fBK2Novo\fP = 3\&.3"
.br
.ti -1c
.RI "const Real \fBK3Novo\fP = 0\&.433"
.br
.ti -1c
.RI "const Real \fBK4Novo\fP = 0\&.323433"
.br
.ti -1c
.RI "const Real \fBTEMP\fP = 386\&.833"
.br
.ti -1c
.RI "const Real \fBRGASNovo\fP = 4\&.157231309"
.br
.in -1c

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
