.TH "ThreeParameters" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ThreeParameters \- Classe base para todas as classes com tres parametros\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ThreeParameters\&.h>\fP
.PP
Subclasse de \fBIsotherm\fP\&.
.PP
Superclasse de \fBBrouersSotolongo\fP\fC [virtual]\fP, \fBBrunauerEmmettTeller\fP\fC [virtual]\fP, \fBFowlerGuggenheim\fP\fC [virtual]\fP, \fBFritzSchlunder\fP\fC [virtual]\fP, \fBHill\fP\fC [virtual]\fP, \fBHillDeboer\fP\fC [virtual]\fP, \fBHollKrich\fP\fC [virtual]\fP, \fBJossens\fP\fC [virtual]\fP, \fBKhan\fP\fC [virtual]\fP, \fBKiselev\fP\fC [virtual]\fP, \fBKobleCorrigan\fP\fC [virtual]\fP, \fBLangmuirFreundlich\fP\fC [virtual]\fP, \fBMacMillanTeller\fP\fC [virtual]\fP, \fBRadkePrausnitsI\fP\fC [virtual]\fP, \fBRadkePrausnitsII\fP\fC [virtual]\fP, \fBRadkePrausnitsIII\fP\fC [virtual]\fP, \fBRedlichPeterson\fP\fC [virtual]\fP, \fBSips\fP\fC [virtual]\fP, \fBToth\fP\fC [virtual]\fP, \fBUnilan\fP\fC [virtual]\fP, \fBValenzuelaMyers\fP\fC [virtual]\fP e \fBViethSladek\fP\fC [virtual]\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBDefineIdentity\fP ('ThreeParameters', ID::ThreeParameters)"
.br
.in -1c
.SS "Membros Protegidos"

.in +1c
.ti -1c
.RI "\fBThreeParameters\fP (const \fBThreeParameters\fP &)=default"
.br
.ti -1c
.RI "\fBThreeParameters\fP (const Real &, const Real &, const Real &)"
.br
.ti -1c
.RI "\fBThreeParameters\fP & \fBoperator=\fP (const \fBThreeParameters\fP &)=default"
.br
.in -1c
.SS "Outros membros herdados"
.SH "Descrição detalhada"
.PP 
Classe base para todas as classes com tres parametros\&. 


.PP
\fBAutores\fP
.RS 4
Lara Botelho Brum 
.PP
Luan Rodrigues Soares de Souza 
.PP
Joao Flavio Vieira de Vasconcellos 
.RE
.PP
\fBVersão\fP
.RS 4
1\&.0 
.RE
.PP
\fBData\fP
.RS 4
2022 
.RE
.PP
\fBBug\fP
.RS 4
Nao ha bugs conhecidos\&.
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
