.TH "Three_Parameters" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Three_Parameters \- Isotermas com tres parametros
.SH SYNOPSIS
.br
.PP
.SS "Módulos"

.in +1c
.ti -1c
.RI "\fBVieth\-Sladek\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Grupo de Isotermas que possuem tres parametros\&. 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
