.TH "Two_Parameters" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Two_Parameters \- Isotermas com dois parametros
.SH SYNOPSIS
.br
.PP
.SS "Módulos"

.in +1c
.ti -1c
.RI "\fBDubinin\-Radushkevich\fP"
.br
.ti -1c
.RI "\fBElovich\fP"
.br
.ti -1c
.RI "\fBFreundlich\fP"
.br
.ti -1c
.RI "\fBIsoterma de Helsey\fP"
.br
.ti -1c
.RI "\fBHarkin\-Jura\fP"
.br
.ti -1c
.RI "\fBJovanovic\fP"
.br
.ti -1c
.RI "\fBLangmuir\fP"
.br
.ti -1c
.RI "\fBTemkin\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Grupo de Isotermas que possuem dois parametros\&. 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
