.TH "TwoParameters" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TwoParameters \- Classe base para todas as classes com dois parametros\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TwoParameters\&.h>\fP
.PP
Subclasse de \fBIsotherm\fP\&.
.PP
Superclasse de \fBDubininRadushkevich\fP\fC [virtual]\fP, \fBElovich\fP\fC [virtual]\fP, \fBFreundlich\fP\fC [virtual]\fP, \fBHalsey\fP\fC [virtual]\fP, \fBHarkinJura\fP\fC [virtual]\fP, \fBJovanovic\fP\fC [virtual]\fP, \fBLangmuir\fP\fC [virtual]\fP e \fBTemkin\fP\fC [virtual]\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBDefineIdentity\fP ('TwoParameters', ID::TwoParameters)"
.br
.in -1c
.SS "Membros Protegidos"

.in +1c
.ti -1c
.RI "\fBTwoParameters\fP (const \fBTwoParameters\fP &)=default"
.br
.ti -1c
.RI "\fBTwoParameters\fP (const Real &_par_0, const Real &_par_1)"
.br
.ti -1c
.RI "\fBTwoParameters\fP & \fBoperator=\fP (const \fBTwoParameters\fP &)=default"
.br
.in -1c
.SS "Outros membros herdados"
.SH "Descrição detalhada"
.PP 
Classe base para todas as classes com dois parametros\&. 


.PP
\fBAutores\fP
.RS 4
Lara Botelho Brum 
.PP
Luan Rodrigues Soares de Souza 
.PP
Joao Flavio Vieira de Vasconcellos 
.RE
.PP
\fBVersão\fP
.RS 4
1\&.0 
.RE
.PP
\fBData\fP
.RS 4
2022 
.RE
.PP
\fBBug\fP
.RS 4
Nao ha bugs conhecidos\&.
.RE
.PP
.PP
\fBCopyright\fP
.RS 4
GNU Public License\&. 
.RE
.PP


.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
