.TH "Type" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Type \- Tipo de Variaveis
.SH SYNOPSIS
.br
.PP
.SS "Definições de Tipos"

.in +1c
.ti -1c
.RI "typedef double \fBReal\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBUInt\fP"
.br
.in -1c
.SH "Descrição detalhada"
.PP 
Definicao do padrao das variaveis inteiras e reais 
.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
