.TH "WeberVanVliet" 3 "Segunda, 3 de Outubro de 2022" "Version 1.0.0" "Isotherm++" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WeberVanVliet \- Classe com as equacoes da isoterma de \fBWeberVanVliet\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <WeberVanVliet\&.h>\fP
.PP
Subclasse de \fBFourParameters\fP e \fBIsothermTemplate< WeberVanVliet >\fP\&.
.SS "Membros Públicos"

.in +1c
.ti -1c
.RI "\fBWeberVanVliet\fP ()=default"
.br
.ti -1c
.RI "\fBWeberVanVliet\fP (const \fBWeberVanVliet\fP &_orig)=default"
.br
.RI "Construtora de copia\&. "
.ti -1c
.RI "virtual \fB~WeberVanVliet\fP ()=default"
.br
.RI "Destrutora\&. "
.ti -1c
.RI "\fBWeberVanVliet\fP (const Real &_k1, const Real &_k2, const Real &_k3, const Real &_k4)"
.br
.RI "Construtora com os parametros que definem a isoterma de \fBWeberVanVliet\fP\&. "
.ti -1c
.RI "\fBWeberVanVliet\fP & \fBoperator=\fP (const \fBWeberVanVliet\fP &_orig)=default"
.br
.RI "Sobrecarga do operador =\&. "
.ti -1c
.RI "Real \fBK1\fP () const"
.br
.RI "Funcao que retorna o coeficiente associado a constante de \fBWeberVanVliet\fP\&. "
.ti -1c
.RI "Real \fBK2\fP () const"
.br
.RI "Funcao que retorna o parametro da equacao de \fBWeberVanVliet\fP\&. "
.ti -1c
.RI "Real \fBK3\fP () const"
.br
.RI "Funcao que retorna o parametro da equacao de \fBWeberVanVliet\fP\&. "
.ti -1c
.RI "Real \fBK4\fP () const"
.br
.RI "Funcao que retorna o parametro da equacao de \fBWeberVanVliet\fP\&. "
.ti -1c
.RI "void \fBK1\fP (const Real &_k1)"
.br
.RI "Funcao que altera o coeficiente associado a constante da isoterma de \fBWeberVanVliet\fP\&. "
.ti -1c
.RI "void \fBK2\fP (const Real &_k2)"
.br
.RI "Funcao que altera o coeficiente associado a constante da isoterma de \fBWeberVanVliet\fP\&. "
.ti -1c
.RI "void \fBK3\fP (const Real &_k3)"
.br
.RI "Funcao para alterar o valor associado a constante da isoterma de \fBWeberVanVliet\fP\&. "
.ti -1c
.RI "void \fBK4\fP (const Real &_k4)"
.br
.RI "Funcao para alterar o valor associado ao expoente da isoterma de \fBWeberVanVliet\fP\&. "
.ti -1c
.RI "Real \fBQe\fP (const Real &_c) const override"
.br
.RI "Funcao que calcula a quantidade de sorcao no equilibrio\&. "
.in -1c
.SS "Outros membros herdados"
.SH "Descrição detalhada"
.PP 
Classe com as equacoes da isoterma de \fBWeberVanVliet\fP\&. 

Isoterma com quatro parametros, $ K_1 $, $ K_2 $ , $ K_3 $ e $ K_4 $, cuja formula e a seguinte: \\begin{align} C_e = K_1 Q(C_e)^{K_2 Q(C_e)^{K_3}+ K_4} \\end{align} Um artigo de referencia pode ser encontrado \fCaqui\fP\&. 
.PP
\fBAutores\fP
.RS 4
Lara Botelho Brum 
.PP
Luan Rodrigues Soares de Souza 
.PP
Joao Flavio Vieira de Vasconcellos 
.RE
.PP
\fBVersão\fP
.RS 4
1\&.0 
.RE
.PP
\fBData\fP
.RS 4
2022 
.RE
.PP
\fBBug\fP
.RS 4
Nao ha bugs conhecidos\&.
.RE
.PP
.PP
\fBCopyright\fP
.RS 4
GNU Public License\&. 
.RE
.PP

.SH "Construtores e Destrutores"
.PP 
.SS "WeberVanVliet::WeberVanVliet ()\fC [default]\fP"

.PP
Construtora default\&. 
.PP
Uso: 
.PP
.nf
WeberVanVliet  var;

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros para esta funcao 
.RE
.PP

.SS "WeberVanVliet::WeberVanVliet (const \fBWeberVanVliet\fP & _orig)\fC [default]\fP"

.PP
Construtora de copia\&. Uso: 
.PP
.nf
WeberVanVliet  var;
WeberVanVliet  var1(var);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_orig\fP Variavel do tipo \fBWeberVanVliet\fP original\&. 
.br
 
.RE
.PP

.SS "WeberVanVliet::WeberVanVliet (const Real & _k1, const Real & _k2, const Real & _k3, const Real & _k4)"

.PP
Construtora com os parametros que definem a isoterma de \fBWeberVanVliet\fP\&. Uso: 
.PP
.nf
double K1(1\&.0);    
double K2(1\&.0);
double K3(0\&.5);
double K4(0\&.5);
WeberVanVliet  var1(K1, K2, K3, K4);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k1\fP Coeficiente da isortema de \fBWeberVanVliet\fP\&. 
.br
 
.br
\fI_k2\fP Coeficiente da isoterma de \fBWeberVanVliet\fP\&. 
.br
\fI_k3\fP Expoente da isoterma de \fBWeberVanVliet\fP\&. 
.br
 
.br
\fI_k4\fP Expoente da isoterma de \fBWeberVanVliet\fP\&. 
.br
 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_k1\fP <= 0\&. 
.br
\fI_k2\fP <= 0\&. 
.br
\fI_k3\fP <= 0\&. 
.RE
.PP

.SH "Funções membros"
.PP 
.SS "Real WeberVanVliet::K1 () const\fC [inline]\fP"

.PP
Funcao que retorna o coeficiente associado a constante de \fBWeberVanVliet\fP\&. Uso: 
.PP
.nf
WeberVanVliet  var1(K1, K2, K3, K4);              
double k1 = var1\&.K1();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor do coeficiente associado a constante de \fBWeberVanVliet\fP\&. 
.RE
.PP

.SS "void WeberVanVliet::K1 (const Real & _k1)\fC [inline]\fP"

.PP
Funcao que altera o coeficiente associado a constante da isoterma de \fBWeberVanVliet\fP\&. Uso: 
.PP
.nf
WeberVanVliet  var1(K1, K2, K3, K4);              
double k1(2\&.0);
var1\&.K1(k1);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k1\fP Novo valor do coeficiente associado a constante da isoterma de \fBWeberVanVliet\fP\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_k1\fP <= 0\&. 
.RE
.PP

.SS "Real WeberVanVliet::K2 () const\fC [inline]\fP"

.PP
Funcao que retorna o parametro da equacao de \fBWeberVanVliet\fP\&. Uso: 
.PP
.nf
WeberVanVliet  var1(K1, K2, K3, K4);              
double k2 = var1\&.K2();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor do parametro da equacao de \fBWeberVanVliet\fP\&. 
.br
 
.RE
.PP

.SS "void WeberVanVliet::K2 (const Real & _k2)\fC [inline]\fP"

.PP
Funcao que altera o coeficiente associado a constante da isoterma de \fBWeberVanVliet\fP\&. Uso: 
.PP
.nf
WeberVanVliet  var1(K1, K2, K3, K4);              
double k2(2\&.0);
var1\&.K2(k2);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k2\fP Novo valor do coeficiente associado a constante da isoterma de \fBWeberVanVliet\fP\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_k2\fP <= 0\&. 
.RE
.PP

.SS "Real WeberVanVliet::K3 () const\fC [inline]\fP"

.PP
Funcao que retorna o parametro da equacao de \fBWeberVanVliet\fP\&. Uso: 
.PP
.nf
WeberVanVliet  var1(K1, K2, K3, K4);              
double k3 = var1\&.K3();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor do parametro da equacao de \fBWeberVanVliet\fP\&. 
.br
 
.RE
.PP

.SS "void WeberVanVliet::K3 (const Real & _k3)\fC [inline]\fP"

.PP
Funcao para alterar o valor associado a constante da isoterma de \fBWeberVanVliet\fP\&. Uso: 
.PP
.nf
WeberVanVliet  var1(K1, K2, K3, K4);              
double k3(0\&.5);
var1\&.K3(k2);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k3\fP Novo valor associado a constante da isoterma de \fBWeberVanVliet\fP\&. 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_k3\fP <= 0\&. 
.br
 
.RE
.PP

.SS "Real WeberVanVliet::K4 () const\fC [inline]\fP"

.PP
Funcao que retorna o parametro da equacao de \fBWeberVanVliet\fP\&. Uso: 
.PP
.nf
WeberVanVliet  var1(K1, K2, K3, K4);              
double k4 = var1\&.K4();

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI \fP Nao ha parametros\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor do parametro da equacao de \fBWeberVanVliet\fP\&. 
.br
 
.RE
.PP

.SS "void WeberVanVliet::K4 (const Real & _k4)\fC [inline]\fP"

.PP
Funcao para alterar o valor associado ao expoente da isoterma de \fBWeberVanVliet\fP\&. Uso: 
.PP
.nf
WeberVanVliet  var1(K1, K2, K3, K4);              
double k4(0\&.5);
var1\&.K4(k4);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_k4\fP Novo valor associado ao expoente da isoterma de \fBWeberVanVliet\fP\&. 
.RE
.PP

.SS "\fBWeberVanVliet\fP & WeberVanVliet::operator= (const \fBWeberVanVliet\fP & _orig)\fC [default]\fP"

.PP
Sobrecarga do operador =\&. Uso: 
.PP
.nf
WeberVanVliet  var1( K1, K2, K3, K4);              
WeberVanVliet  var2 = var1;

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_orig\fP Variavel do tipo \fBWeberVanVliet\fP\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Copia de _orig\&. 
.br
 
.RE
.PP

.SS "Real WeberVanVliet::Qe (const Real & _c) const\fC [inline]\fP, \fC [override]\fP, \fC [virtual]\fP"

.PP
Funcao que calcula a quantidade de sorcao no equilibrio\&. Uso: 
.PP
.nf
WeberVanVliet  var1(K1, K2, K3, K4);              
double ce(1\&.0);
double qe = var1\&.Qe(ce);

.fi
.PP
 
.PP
\fBParâmetros\fP
.RS 4
\fI_c\fP Concentracao do soluto\&. 
.RE
.PP
\fBRetorna\fP
.RS 4
Valor da quantidade de sorcao no equilibrio\&. 
.br
 
.RE
.PP
\fBExceções\fP
.RS 4
\fI_c\fP <= 0\&. 
.br
 
.RE
.PP

.PP
Reimplementa \fBIsotherm\fP\&.

.SH "Autor"
.PP 
Gerado automaticamente por Doxygen para Isotherm++ a partir do código-fonte\&.
