var searchData=
[
  ['id_0',['ID',['../class_i_d.html',1,'']]],
  ['identificação_20da_20classe_1',['Identificação da Classe',['../group___i_d.html',1,'']]],
  ['informações_20sobre_20as_20classes_2',['Informações sobre as classes',['../group___source_info.html',1,'']]],
  ['isoexception_3',['IsoException',['../class_iso_exception.html',1,'']]],
  ['isoexception_2eh_4',['IsoException.h',['../_iso_exception_8h.html',1,'']]],
  ['isoterma_20de_20frenkel_2dhalsey_2dhill_2e_5',['Isoterma de Frenkel-Halsey-Hill.',['../group___frenkel_halsey_hill.html',1,'']]],
  ['isoterma_20de_20helsey_6',['Isoterma de Helsey',['../group___halsey.html',1,'']]],
  ['isotermas_20com_20cinco_20parâmetros_7',['Isotermas com cinco parâmetros',['../group___five___parameters.html',1,'']]],
  ['isotermas_20com_20dois_20parâmetros_8',['Isotermas com dois parâmetros',['../group___two___parameters.html',1,'']]],
  ['isotermas_20com_20quatro_20parâmetros_9',['Isotermas com quatro parâmetros',['../group___four___parameters.html',1,'']]],
  ['isotermas_20com_20três_20parâmetros_10',['Isotermas com três parâmetros',['../group___three___parameters.html',1,'']]],
  ['isotermas_20com_20um_20parâmetro_11',['Isotermas com um parâmetro',['../group___one___parameter.html',1,'']]],
  ['isotherm_12',['Isotherm',['../class_isotherm.html',1,'']]],
  ['isothermtemplate_13',['IsothermTemplate',['../class_isotherm_template.html',1,'IsothermTemplate&lt; T &gt;'],['../group___isotherm_template.html',1,'(<em>Namespace</em> global)']]],
  ['isothermtemplate_3c_20brouerssotolongo_20_3e_14',['IsothermTemplate&lt; BrouersSotolongo &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20brunaueremmettteller_20_3e_15',['IsothermTemplate&lt; BrunauerEmmettTeller &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20dubininradushkevich_20_3e_16',['IsothermTemplate&lt; DubininRadushkevich &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20elovich_20_3e_17',['IsothermTemplate&lt; Elovich &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20fowlerguggenheim_20_3e_18',['IsothermTemplate&lt; FowlerGuggenheim &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20frenkelhalseyhill_20_3e_19',['IsothermTemplate&lt; FrenkelHalseyHill &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20freundlich_20_3e_20',['IsothermTemplate&lt; Freundlich &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20fritzschlunder_20_3e_21',['IsothermTemplate&lt; FritzSchlunder &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20fritzschlunderiv_20_3e_22',['IsothermTemplate&lt; FritzSchlunderIV &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20fritzschlunderv_20_3e_23',['IsothermTemplate&lt; FritzSchlunderV &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20halsey_20_3e_24',['IsothermTemplate&lt; Halsey &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20harkinjura_20_3e_25',['IsothermTemplate&lt; HarkinJura &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20henderson_20_3e_26',['IsothermTemplate&lt; Henderson &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20henry_20_3e_27',['IsothermTemplate&lt; Henry &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20hill_20_3e_28',['IsothermTemplate&lt; Hill &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20hilldeboer_20_3e_29',['IsothermTemplate&lt; HillDeboer &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20hollkrich_20_3e_30',['IsothermTemplate&lt; HollKrich &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20jossens_20_3e_31',['IsothermTemplate&lt; Jossens &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20jovanovic_20_3e_32',['IsothermTemplate&lt; Jovanovic &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20khan_20_3e_33',['IsothermTemplate&lt; Khan &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20kiselev_20_3e_34',['IsothermTemplate&lt; Kiselev &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20koblecorrigan_20_3e_35',['IsothermTemplate&lt; KobleCorrigan &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20langmuir_20_3e_36',['IsothermTemplate&lt; Langmuir &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20langmuirfreundlich_20_3e_37',['IsothermTemplate&lt; LangmuirFreundlich &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20langmuirjovanovic_20_3e_38',['IsothermTemplate&lt; LangmuirJovanovic &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20macmillanteller_20_3e_39',['IsothermTemplate&lt; MacMillanTeller &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20radkeprausnitsi_20_3e_40',['IsothermTemplate&lt; RadkePrausnitsI &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20radkeprausnitsii_20_3e_41',['IsothermTemplate&lt; RadkePrausnitsII &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20radkeprausnitsiii_20_3e_42',['IsothermTemplate&lt; RadkePrausnitsIII &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20redlichpeterson_20_3e_43',['IsothermTemplate&lt; RedlichPeterson &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20sips_20_3e_44',['IsothermTemplate&lt; Sips &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20temkin_20_3e_45',['IsothermTemplate&lt; Temkin &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20toth_20_3e_46',['IsothermTemplate&lt; Toth &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20unilan_20_3e_47',['IsothermTemplate&lt; Unilan &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20valenzuelamyers_20_3e_48',['IsothermTemplate&lt; ValenzuelaMyers &gt;',['../class_isotherm_template.html',1,'']]],
  ['isothermtemplate_3c_20viethsladek_20_3e_49',['IsothermTemplate&lt; ViethSladek &gt;',['../class_isotherm_template.html',1,'']]],
  ['ist_5fnamespace_5fclose_50',['IST_NAMESPACE_CLOSE',['../group___configure.html#ga9804ef63a551808d389310b891356c2a',1,'Configure.h']]],
  ['ist_5fnamespace_5fopen_51',['IST_NAMESPACE_OPEN',['../group___configure.html#ga1e3e0e0eca304ffc8364100b22724d21',1,'Configure.h']]]
];
